Amelchenko_Dima/hw 25
eugene-okulik/QAP-10onl pull request #127
Opened 2023-01-07 17:29 UTC by AmelchenkoDima

2023-01-09 07:28 UTC, eugene-okulik requested changes

2023-01-09 07:28 UTC, eugene-okulik commented on homework/Dima_Amelchenko/HW_25/test_api_meme_hw_25.py
> +    assert response['id'] == 225
Этот тест одноразовый. Один раз ты изменишь что-то в меме этим тестом. Когда в следующий раз ты запустишь этот тест, мем итак уже будет содержать ту информацию, которую ты хочешь в него добавить.

2023-01-09 07:28 UTC, eugene-okulik commented on homework/Dima_Amelchenko/HW_25/test_api_meme_hw_25.py
> +    meme_id = yield response['id']
А для чего здесь генерация id?

2023-01-09 07:28 UTC, eugene-okulik commented on homework/Dima_Amelchenko/HW_25/test_api_meme_hw_25.py
> +    response = requests.request('GET', f'{domain}/meme/224', headers=headers)
А здесь id мема захардкожено. Этот тест всегда будет проходить успешно, даже если удаление не сработало.

2023-01-09 07:28 UTC, eugene-okulik commented on homework/Dima_Amelchenko/HW_25/test_api_meme_hw_25.py
> +    assert response.status_code == 401
Код 401 - отказ в доступе. Такой код получается если ты пытаешься удалить не свой мем или если ты не авторизван (обратился без валидного токена)

2023-01-09 07:28 UTC, eugene-okulik commented on homework/Dima_Amelchenko/HW_25/conftest.py
> +TOKEN = 'TtezNG3Zq8La1zB'
Токен - вещь не постоянная. Он в какой-то момент перестает существовать и нужно или перед каждым запуском получать новый или как-то хранить старый и перед запуском проверять жив ли он.

2023-01-12 05:25 UTC, eugene-okulik commented on homework/Dima_Amelchenko/HW_25/conftest.py
> +    )
Здесь проблема с отступами. Локально линт на это почему-то не ругается. Поэтому не могу проверить как ему понравится. Но по идее отступы должны идти так:
```python
    data = json.dumps(
        {
            "text": "Family",
            "url": "https://www.thevoicemag.ru/upload/img_cache/f0e/f0e1c3b4b532fbc70a73e022ffcf35f2_fitted_1332x0.jpg",
            "tags": ["fun", "Vin Diesel"],
            "info": {"type": "jpg"}
        }
    )
```
Сегодня в начале занятия покажу как чинить такое с помощью пайчарма

2023-01-12 05:28 UTC, eugene-okulik commented on homework/Dima_Amelchenko/HW_25/test_api_meme_hw_25.py
> +            f"id": {add_meme}, "text": "Family",
Здесь f-string применен не там. Должно быть 
```python
"id": f"{add_meme}", "text": "Family",
```
А на самом деле, все еще проще:
```python
"id": add_meme, "text": "Family",
```

2023-01-12 05:34 UTC, eugene-okulik commented on homework/Dima_Amelchenko/HW_25/test_api_meme_hw_25.py
> +        }
На строчки 13 и 15 линт тоже ругается, но здесь все нормально. Странно. Может, передумает.

2023-01-12 05:37 UTC, eugene-okulik commented on homework/Dima_Amelchenko/HW_25/test_api_meme_hw_25.py
> +        }
На крайняк, если он таки будет продолжать ругаться, попробуй ему скормить так:
```python
    data = json.dumps(
        {
            "text": "Family",
            "url": "https://www.thevoicemag.ru/upload/img_cache/f0e/f0e1c3b4b532fbc70a73e022ffcf35f2_fitted_1332x0.jpg",
            "tags": [
                "fun", 
                "Vin Diesel"
            ],
            "info": {
                "type": "jpg"
            }
        }
    )
```
Может, он считает, что раз уж переносы, то пусть все будет с переносами.

2023-01-12 05:38 UTC, eugene-okulik commented on homework/Dima_Amelchenko/HW_25/test_api_meme_hw_25.py
> +        }
здесь в строчках 30 и 32 тоже непонятно что ему не нравится. Попробуй тоже попереносить содержимое тегов и инфо

2023-01-12 07:42 UTC, AmelchenkoDima commented
Все сработало спасибо )

2023-01-16 07:08 UTC, eugene-okulik approved these changes
Да, теперь норм. Только файлик с токеном лучше не заливать на гитхаб. Для этой нашей апишки это не страшно, но обычно заливание такого - дыра в безопасности всего тестируемого приложения.

2023-01-16 07:08 UTC, eugene-okulik commented on homework/Dima_Amelchenko/HW_25/conftest.py
> +TOKEN = open('token.txt', 'r').read()
Файл остается незакрытым. Если будешь запускать в несколько потоков, могут появиться проблемы. Лучше использовать менеджер контекста:
```python
with open('token.txt', 'r') as token_file:
    TOKEN = token_file.read()
```
Такое оформление гарантирует, что после прочтения файл будет закрыт.

2023-01-16 07:08 UTC, merged