Sergey_Zapashchykov:Homework_27_done
eugene-okulik/QAP-10onl pull request #131
Opened 2023-01-10 13:47 UTC by SergeyZapashchykov

2023-01-16 07:35 UTC, eugene-okulik requested changes

2023-01-16 07:35 UTC, eugene-okulik commented on homework/sergey_zapashchykov/homework_27/task_27.py
> +group_value = (4, 'QAP-10', '2022-01-10', '2023-01-10')
Id обычно не указывают при инсерте данных в базу. Такой код - одноразовый. Чтобы еще раз его запустить, тебе предварительно придется изменить id руками в коде, т.к. база данных не сможет вставить запись с таким id, ведь такая запись уже есть.
Это касается всех инсертов у тебя в коде.

2023-01-16 11:29 UTC, SergeyZapashchykov commented
Поправил INSERT и понял, почему ты на занятии говорил, что вам пригодится lastrowid, как раз чтобы код сделать не одноразовым, спасибо за наводку).
Готово к проверке.

2023-01-18 05:44 UTC, eugene-okulik commented
> Поправил INSERT и понял, почему ты на занятии говорил, что вам пригодится lastrowid, как раз чтобы код сделать не одноразовым, спасибо за наводку). Готово к проверке.

:+1:

2023-01-18 05:44 UTC, eugene-okulik approved these changes

2023-01-18 05:44 UTC, merged