Alesia Kurylenka: homework 17 completed
eugene-okulik/QAP-10onl pull request #25
Opened 2022-11-26 17:42 UTC by akurylenka

2022-11-27 07:28 UTC, eugene-okulik requested changes

2022-11-27 07:28 UTC, eugene-okulik commented on homework/alesia_kurylenka/homework_17/task_17_4.txt
> +sudo chmod -R g=r-x /home/akurylenka
Эта команда добавляет для группы право на чтение и убирает право на выполнение. А нужно и то и другое право добавить

2022-11-27 16:43 UTC, akurylenka commented on homework/alesia_kurylenka/homework_17/task_17_4.txt
> +sudo chmod -R g=r-x /home/akurylenka
@eugene-okulik fixed, please recheck

2022-12-01 06:49 UTC, eugene-okulik approved these changes

2022-12-01 06:49 UTC, merged