Evgeny Sporshev homework_19
eugene-okulik/QAP-10onl pull request #47
Opened 2022-12-03 20:56 UTC by verygnawtyatwork

Просьба проверить.

2022-12-04 09:49 UTC, eugene-okulik requested changes
Похоже, ты забыл заполнить поле загрузки файла

2022-12-04 09:49 UTC, eugene-okulik commented on homework/evgeny_sporshev/homework_19/hw_19_1.py
> +    state.click()
На этом моменте селениуму не удается кликнуть туда куда ты пытался - реклама мешает.  Бывает что селениум сам подкручивает туда, куда надо, а бывает нет, в таких ситуациях можно помочь ему - проскроллить страницу до конца.
```python
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
```
Чуть детальнее разберем что это такое на ближайших занятиях. Но пока можешь скопипастить ))

2022-12-05 10:35 UTC, verygnawtyatwork commented
Добавил строчку "driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")". Очень странно, потому как у меня и без нее работало - ошибок не выскакивало. Быть может это зависит от размера экрана (у меня 15 дюймовый ноут).

2022-12-06 07:59 UTC, eugene-okulik commented
> Добавил строчку "driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")". Очень странно, потому как у меня и без нее работало - ошибок не выскакивало. Быть может это зависит от размера экрана (у меня 15 дюймовый ноут).

Ага, скорее всего это из-за размера экрана

2022-12-06 08:00 UTC, eugene-okulik commented
Что там с загрузкой файла? Сделаешь?

2022-12-06 08:05 UTC, eugene-okulik approved these changes

2022-12-06 08:05 UTC, merged