Evgeny Sporshev homework20
eugene-okulik/QAP-10onl pull request #58
Opened 2022-12-07 21:05 UTC by verygnawtyatwork

Просьба проверить.

2022-12-12 09:24 UTC, eugene-okulik requested changes
`Before current test:` печатается не перед каждым тестом.  
Если запустить так `pytest -v -s test_hw_20.py::test_three`, то не печатается `Hello to all tests!`

2022-12-16 21:39 UTC, verygnawtyatwork commented
> `Before current test:` печатается не перед каждым тестом. Если запустить так `pytest -v -s test_hw_20.py::test_three`, то не печатается `Hello to all tests!`

Исправил 
![image](https://user-images.githubusercontent.com/69771592/208193301-f5c96c62-c775-4770-af54-45afd8c61d99.png)

2022-12-18 12:05 UTC, eugene-okulik requested changes
Для тестов с четвертого по последний не печатается `Before current test:`

2022-12-19 10:12 UTC, verygnawtyatwork commented
> Для тестов с четвертого по последний не печатается `Before current test:`

хм, вроде такого требования не было, но добавил ко всем тестам, просьба - посмотреть.

2022-12-22 10:36 UTC, eugene-okulik commented
> > Для тестов с четвертого по последний не печатается `Before current test:`
> 
> хм, вроде такого требования не было, но добавил ко всем тестам, просьба - посмотреть.

было ж вот это:
> Добавьте действие, которое отрабатывает до и после каждого теста

2022-12-22 10:37 UTC, eugene-okulik approved these changes

2022-12-22 10:37 UTC, merged