Evgeny Sporshev homework 21
eugene-okulik/QAP-10onl pull request #76
Opened 2022-12-11 22:31 UTC by verygnawtyatwork

Просьба проверить

2022-12-12 10:31 UTC, eugene-okulik commented on homework/evgeny_sporshev/homework_21/test_hw_21_2.py
> +    sub_sub_item = driver.find_element(By.XPATH, '//ul[@id="nav"]/li[2]/ul/li[3]/ul/li[2]')
Локаторы - не очень, но тот вариант, который здесь больше подходит (поиск по тексту) работает нестабильно, поэтому в этом тесте таки принимаются ))

2022-12-12 10:33 UTC, eugene-okulik requested changes

2022-12-12 10:33 UTC, eugene-okulik commented on homework/evgeny_sporshev/homework_21/test_hw_21_3.py
> +    prompt_return = driver.find_element(By.XPATH, '//div[@class="centered"][3]/p[1]')
Этот элемент же прям по ID ищется проще простого.

2022-12-12 11:10 UTC, verygnawtyatwork commented
"Этот элемент же прям по ID ищется проще простого" слона-то я и не заметил. Переделал.

2022-12-15 05:53 UTC, eugene-okulik approved these changes

2022-12-15 05:54 UTC, merged