homework 22
eugene-okulik/QAP-10onl pull request #78
Opened 2022-12-12 14:23 UTC by Raikhelson

2022-12-15 06:22 UTC, eugene-okulik requested changes
Задание выполнено хорошо. Мне понравилось, что ты собрала много общих методов в бейс пейдже.  
Но слипы - зло. Их нужно использовать в очень крайних случаях. И здесь, похоже, не он ))
И все-таки синхронизируй свой репозиторий с моим. Там все время появляются изменения, касающиеся всего проекта. Например, если бы наши репозитории были синхронизированы, папки pycache не залились бы в гитхаб. Но и в целом пытайся контролировать, чтобы лишнее в гитхаб не улетало.

2022-12-15 06:22 UTC, eugene-okulik commented on homework/valerie_raikhelson/homework_22/luna_store/pages/eco_friendly.py
> +from selenium.webdriver import ActionChains
Этот импорт не используется. Нужно такое удалять.

2022-12-15 06:22 UTC, eugene-okulik commented on homework/valerie_raikhelson/homework_22/luna_store/pages/eco_friendly.py
> +        sleep(3)
Этот слип должен быть заменен на WebDriverWait. Если не получается, - спрашивай

2022-12-16 14:13 UTC, Raikhelson commented on homework/valerie_raikhelson/homework_22/luna_store/pages/eco_friendly.py
> +        sleep(3)
исправлено

2022-12-16 14:15 UTC, Raikhelson commented on homework/valerie_raikhelson/homework_22/luna_store/pages/eco_friendly.py
> +from selenium.webdriver import ActionChains
сделала pull ) я  до этого просто все домахи в один день зафигачила и поэтому  не делала pull .....(((

2022-12-18 12:08 UTC, eugene-okulik approved these changes
Папку `reports` тоже не нужно заливать в гитхаб

2022-12-18 12:08 UTC, merged