Olga Aviltseva /  homework22
eugene-okulik/QAP-10onl pull request #82
Opened 2022-12-14 20:12 UTC by Olgaaviltseva

2022-12-15 06:45 UTC, eugene-okulik requested changes
Посмотри комментарии и добавь тесты. В задании было "Создать по три теста для каждой из этих страниц"

2022-12-15 06:45 UTC, eugene-okulik commented on homework/olga_aviltseva/luma_store/pages/base_page.py
> +        WebDriverWait(self.driver, 10).until(ec.element_to_be_clickable(self.driver.find_element(*locator)))
Этот метод прикольный, но странно, что сначала ты элемент кликаешь, а потом его ждешь.

2022-12-15 06:45 UTC, eugene-okulik commented on homework/olga_aviltseva/luma_store/pages/create_an_account_page.py
> +from pages.locators import create_an_account_page as loc
Обычно артикли в именах файлов пропускаются, чтобы не делать слишком длинные названия. Это я про `create_an_account_page`

2022-12-15 06:45 UTC, eugene-okulik commented on homework/olga_aviltseva/luma_store/tests/test_create_account.py
> +    assert create_account.compare_password().__contains__('Please enter the same value again.')
Такую проверку обычно делают с помощью проверки на вхождение 
```python
assert  'Please enter the same value again.' in create_account.compare_password()
```

2022-12-15 06:45 UTC, eugene-okulik commented on homework/olga_aviltseva/luma_store/pages/eco_friendly_page.py
> +        return len(self.find_all(loc.products_list))
Лучше методы называть тем, что они возвращают. Если они проверяют что-то и возвращают `True` или `False`, то отлично подходит название, начинающееся на `check_`, но этот метод возвращает количество, можно назвать его так, чтобы это было понятно из названия. И тогда проверка `assert eco_friendly.check_12_products_on_the_page() == 12` не будет выглядеть нелогичной.

2022-12-27 19:57 UTC, Olgaaviltseva commented
Исправила, посмотри, пожалуйста.

2022-12-29 06:03 UTC, eugene-okulik requested changes

2022-12-29 06:03 UTC, eugene-okulik commented on homework/olga_aviltseva/luma_store/tests/test_create_account.py
>      create_account.click_create_account_button()
А для чего ты кликаешь здесь кнопку? Ведь сообщение о пароле появляется сразу после того как введен пароль.

2022-12-29 06:03 UTC, eugene-okulik commented on homework/olga_aviltseva/luma_store/tests/test_eco_friendly.py
> +    sleep(3)  # Оставила специально, не забыла убрать
В комментарии возле слипа нужно указать почему он не заменен на `WebDriverWait`

2022-12-29 06:03 UTC, eugene-okulik commented
Если бы не было слипов, то принял бы, но со слипами не пропущу )))

2023-01-06 14:46 UTC, Olgaaviltseva commented
Поправила ошибки, плюс есть изменения для домашней работу по allure.  Как в данном случае слип заменить на wait не знаю (отписала в комментариях к коду). На реальном проекте можно было бы  уточнить у разработчиков как работает сайт и попробовать решить, но тут могу только заменить тесты на другие без слипов.

2023-01-08 07:52 UTC, eugene-okulik requested changes
В принципе, поэтому я и прошу указывать почему не заменен слип на ожидание. Использование ожиданий - очень ранообразная штука и нужно научиться находить способы иго применения. Все ситуации показать на занятии невозможно. И вот когда ты попробовала и не получилось, ты указываешь это и я тебе подсказываю как можно поступить в этой ситуации. Все возможные ситуации все равно не рассмотрим, но зато ты поймешь в какие направления смотреть, когда возникает что-то такое.
И еще: папочку `reports` не нужно заливать в гитхаб, т.к. это результат работы кода, а в гитхаб заливаются только сам код.

2023-01-08 07:52 UTC, eugene-okulik commented on homework/olga_aviltseva/luma_store/tests/test_eco_friendly.py
> +    # не успевает срабатывать, поэтому стоит слип
В такой ситуации нужно смотреть что на странице загружается самым последним. Часто это бывает достаточно сложно, но на этой странице все попроще. Если поперезагружать ее много раз, можно заметить, что текст "Default welcome msg!" появляется на странице самым последним. Вот его и можно подождать:
```python
WebDriverWait(driver, 10).until(EC.text_to_be_present_in_element((By.TAG_NAME, 'body'), 'Default welcome msg!'))
```
Появление этого текста говорит о том, что страница полностю загружена.

2023-01-08 07:52 UTC, eugene-okulik commented on homework/olga_aviltseva/luma_store/tests/test_create_account.py
> +        # появляется, нужно или с клавиатуры вводить или кликать что-нибудь, поэтому здесь на кнопку
Здесь проблема тоже в том, что страница не до конца загрузилась. Нужно дождаться загрузки страницы - и только после этого вводить пароль. Тогда все работает без слипов и клика. Выглядит все вот так:
```python
def test_massage_strong_password(driver):
    with allure.step('Open Create Account page'):
        create_account = CreateAnAccount(driver)
        create_account.open()
    with allure.step('Scroll page'):
        create_account.scroll_page()
    with allure.step('Enter password'):
        WebDriverWait(driver, 10).until(EC.text_to_be_present_in_element((By.TAG_NAME, 'body'), 'Default welcome msg!'))
        create_account.send_password('Password2022')
    with allure.step('Wait'):
        # sleep(3)  # Не заменен  на WebDriverWait так как на странице ничего не меняется, из за быстрых кликов автотеста
        # не успевает срабатывать, поэтому стоит слип
        # create_account.click_create_account_button()  # Когда пароль отправляется автотестом, то сообщение не
        # появляется, нужно или с клавиатуры вводить или кликать что-нибудь, поэтому здесь на кнопку
        assert create_account.get_password_message() == 'Very Strong'
```

2023-01-08 10:16 UTC, Olgaaviltseva commented
Спасибо, поправила

2023-01-09 06:58 UTC, eugene-okulik approved these changes

2023-01-09 06:58 UTC, merged