homework 23
eugene-okulik/QAP-10onl pull request #83
Opened 2022-12-14 21:28 UTC by Raikhelson

2022-12-19 05:52 UTC, eugene-okulik approved these changes
Обрати внимание, что у нас есть требования к тому как называть ветки, коммиты и пулл реквесты.  
Эти правила всгда будут существовать, если ты будешь работать не сама на себя. Но и даже если работаешь сама на себя, придется придумать себе правила, чтобы не запутаться в том, что делаешь.  
https://github.com/eugene-okulik/QAP-10onl/wiki/%D0%98%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B1%D1%80%D0%B0%D0%BD%D1%87%D0%B5%D0%B9,-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82%D0%BE%D0%B2,-%D0%BF%D1%83%D0%BB%D0%BB-%D1%80%D0%B5%D0%BA%D0%B2%D0%B5%D1%81%D1%82%D0%BE%D0%B2

2022-12-19 05:53 UTC, eugene-okulik requested changes
Файлы залиты не в твою папку, а в корень проекта.

2023-01-16 06:46 UTC, eugene-okulik commented
Сейчас нужно синхронизировать ветку `main` твоего репозитория с веткой `main` моего репозитория. После этого вмержить ветку `main` в ветку `Raikhelson:homework23`. Это должно решить конфликты. Пока что нет никакой возможности смержить твою работу в мой репозиторий

2023-01-20 13:01 UTC, Raikhelson commented
это  я должна сделать :
- git checkout main
 - git pull main
 - git merge origin homework23?
 Поправь  пожалуйста пока не натворила делов)

2023-01-20 13:40 UTC, closed without merging