Alesia Kurylenka: homework_22 completed
eugene-okulik/QAP-10onl pull request #85
Opened 2022-12-14 22:50 UTC by akurylenka

2022-12-18 12:20 UTC, eugene-okulik requested changes

2022-12-18 12:20 UTC, eugene-okulik commented on homework/alesia_kurylenka/homework_22/magento_project/conftest.py
> +    sleep(3)
Из готового кода слипы нужно удалять. Если нужно чего-то подождать, правильно будет использовать WebDriverWait.

2022-12-18 12:20 UTC, eugene-okulik commented on homework/alesia_kurylenka/homework_22/magento_project/pages/base_page.py
> +        self.driver.execute_script("document.body.style.zoom = '0.5'")
Такие методы лучше делать универсальными: не хардкодить 0.5, а передевать его в этот метод.

2022-12-18 12:20 UTC, eugene-okulik commented on homework/alesia_kurylenka/homework_22/magento_project/pages/create_an_account_page.py
> +    def is_present_create_account_button(self):
Исходя из названия этого метода, я предполагаю, что он взвращает `True` или `False`, но он возвращает текст. Логичнее было бы назвать метод  `create_account_button_text`

2022-12-18 12:20 UTC, eugene-okulik commented on homework/alesia_kurylenka/homework_22/magento_project/pages/sale_page.py
> +    def gear_deals_menu(self):
А этот метод что-то проверяет. Можно и назвать так, чтобы это было понятно из названия.

2022-12-18 18:55 UTC, akurylenka commented on homework/alesia_kurylenka/homework_22/magento_project/pages/sale_page.py
> +    def gear_deals_menu(self):
@eugene-okulik  all comments fixed, please double check

2022-12-19 05:33 UTC, eugene-okulik approved these changes

2022-12-19 05:33 UTC, merged