Amelchenko_Dima_hw_22
eugene-okulik/QAP-10onl pull request #97
Opened 2022-12-18 16:21 UTC by AmelchenkoDima

2022-12-19 05:48 UTC, eugene-okulik requested changes
Для каждой страницы всего по одному тесту, а нужно было 3 для каждой.  
Если для одной страницы локаторы убираешь в отдельный файл, то нужно для всех страниц делать так же.  
Названия классов страниц тоже должны соответствовать одному шаблону. Или во всех есть слово `Page`, или во всех нет.

2022-12-25 17:44 UTC, AmelchenkoDima commented
Очень хотел сделать проверку с выпадающим списком.
Но столкнулся с проблемой что страница при автотесте не обновляется при выборе "Price" в выпадающем списке на страннице https://magento.softwaretestingboard.com/collections/eco-friendly.html
Возможно ты подскажешь в чем там проблема

2022-12-29 06:25 UTC, eugene-okulik approved these changes

2022-12-29 06:25 UTC, eugene-okulik commented on homework/Dima_Amelchenko/HW_22/pages/create_new_customer_account_page.py
> +        self.find(locator_1.email).send_keys('malevichkazimir249@gmail.com')
Получается, тебе перед каждым запуском нужно будет идти в тес и менять этот емейл. Можно сделать, чтобы он генерился рандомом, тогда тест будет вечным.

2022-12-29 06:25 UTC, eugene-okulik commented on homework/Dima_Amelchenko/HW_22/pages/sale_page.py
> +    def check_men_s_bargains(self):
Методы хорошо бы называть тем, что они делают. Например, этот метод ничего не проверяет, а возвращает текст. Поэтому ему бы подошло название `mens_bargains_text`

2022-12-29 06:28 UTC, eugene-okulik commented
> Очень хотел сделать проверку с выпадающим списком. Но столкнулся с проблемой что страница при автотесте не обновляется при выборе "Price" в выпадающем списке на страннице https://magento.softwaretestingboard.com/collections/eco-friendly.html Возможно ты подскажешь в чем там проблема

Эксперименты показали, что для того, чтобы на этой странице что-то работало, прежде чем что-то на ней трогать, нужно дождаться пока она полностью загрузится. Вот так вот, например, работает:
```python
from selenium import webdriver
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


driver = webdriver.Chrome()
driver.maximize_window()
driver.implicitly_wait(10)
driver.get('https://magento.softwaretestingboard.com/collections/eco-friendly.html')
dropdown = Select(driver.find_element(By.ID, 'sorter'))
WebDriverWait(driver, 10).until(EC.text_to_be_present_in_element((By.TAG_NAME, 'body'), 'Default welcome msg! '))
dropdown.select_by_value('price')
WebDriverWait(driver, 10).until(EC.url_contains('price'))
```

2022-12-29 06:28 UTC, merged